async function request(path, options = {}) {
  const res = await fetch(path, {
    headers: { 'Content-Type': 'application/json', ...(options.headers || {}) },
    ...options,
    body: options.body ? JSON.stringify(options.body) : undefined
  })
  const data = await res.json().catch(() => ({}))
  if (!res.ok) {
    const err = new Error(data.message || `Request failed (${res.status})`)
    err.status = res.status
    err.data = data
    throw err
  }
  return data
}

export const api = {
  health: () => request('/api/health'),
  dashboard: () => request('/api/dashboard'),
  settings: () => request('/api/settings'),
  saveDc: (body) => request('/api/settings/domain-controller', { method: 'PUT', body }),
  saveAzure: (body) => request('/api/settings/azure-ad', { method: 'PUT', body }),
  testDc: (body) => request('/api/settings/domain-controller/test', { method: 'POST', body: body || {} }),
  testAzure: (body) => request('/api/settings/azure-ad/test', { method: 'POST', body: body || {} }),
  sync: () => request('/api/settings/sync', { method: 'POST', body: {} }),
  users: (q) => request(`/api/users${q || ''}`),
  user: (id) => request(`/api/users/${id}`),
  createUser: (body) => request('/api/users', { method: 'POST', body }),
  updateUser: (id, body) => request(`/api/users/${id}`, { method: 'PUT', body }),
  enableUser: (id) => request(`/api/users/${id}/enable`, { method: 'POST', body: {} }),
  disableUser: (id) => request(`/api/users/${id}/disable`, { method: 'POST', body: {} }),
  unlockUser: (id) => request(`/api/users/${id}/unlock`, { method: 'POST', body: {} }),
  resetPassword: (id) => request(`/api/users/${id}/reset-password`, { method: 'POST', body: {} }),
  deleteUser: (id) => request(`/api/users/${id}`, { method: 'DELETE' }),
  computers: (q) => request(`/api/computers${q || ''}`),
  computer: (id) => request(`/api/computers/${id}`),
  createComputer: (body) => request('/api/computers', { method: 'POST', body }),
  updateComputer: (id, body) => request(`/api/computers/${id}`, { method: 'PUT', body }),
  enableComputer: (id) => request(`/api/computers/${id}/enable`, { method: 'POST', body: {} }),
  disableComputer: (id) => request(`/api/computers/${id}/disable`, { method: 'POST', body: {} }),
  deleteComputer: (id) => request(`/api/computers/${id}`, { method: 'DELETE' }),
  groups: (q) => request(`/api/groups${q || ''}`),
  group: (id) => request(`/api/groups/${id}`),
  createGroup: (body) => request('/api/groups', { method: 'POST', body }),
  updateGroup: (id, body) => request(`/api/groups/${id}`, { method: 'PUT', body }),
  addMember: (id, memberId) => request(`/api/groups/${id}/members`, { method: 'POST', body: { memberId } }),
  removeMember: (id, memberId) => request(`/api/groups/${id}/members/${memberId}`, { method: 'DELETE' }),
  deleteGroup: (id) => request(`/api/groups/${id}`, { method: 'DELETE' }),
  gpos: (q) => request(`/api/gpos${q || ''}`),
  gpo: (id) => request(`/api/gpos/${id}`),
  createGpo: (body) => request('/api/gpos', { method: 'POST', body }),
  updateGpo: (id, body) => request(`/api/gpos/${id}`, { method: 'PUT', body }),
  deleteGpo: (id) => request(`/api/gpos/${id}`, { method: 'DELETE' }),
  shares: (q) => request(`/api/shares${q || ''}`),
  share: (id) => request(`/api/shares/${id}`),
  createShare: (body) => request('/api/shares', { method: 'POST', body }),
  updateShare: (id, body) => request(`/api/shares/${id}`, { method: 'PUT', body }),
  deleteShare: (id) => request(`/api/shares/${id}`, { method: 'DELETE' }),
  laps: (q) => request(`/api/laps${q || ''}`),
  lapsOne: (id) => request(`/api/laps/${id}`),
  createLaps: (body) => request('/api/laps', { method: 'POST', body }),
  rotateLaps: (id) => request(`/api/laps/${id}/rotate`, { method: 'POST', body: {} }),
  audit: (q) => request(`/api/audit${q || ''}`),
  reports: () => request('/api/reports'),
  ous: () => request('/api/ous'),
  ou: (id) => request(`/api/ous/${id}`),
  createOu: (body) => request('/api/ous', { method: 'POST', body }),
  moveObject: (body) => request('/api/ous/move', { method: 'POST', body }),
  hybrid: () => request('/api/hybrid'),
  hybridSync: (userId) => request(`/api/hybrid/${userId}/sync`, { method: 'POST', body: {} }),
  jit: () => request('/api/jit'),
  createJit: (body) => request('/api/jit', { method: 'POST', body }),
  revokeJit: (id) => request(`/api/jit/${id}/revoke`, { method: 'POST', body: {} }),
  passwordPolicies: () => request('/api/password-policies'),
  createPso: (body) => request('/api/password-policies', { method: 'POST', body }),
  updatePso: (id, body) => request(`/api/password-policies/${id}`, { method: 'PUT', body }),
  simulatePassword: (body) => request('/api/password-policies/simulate', { method: 'POST', body }),
  gpoRsop: (id, ou) => request(`/api/gpos/${id}/rsop${ou ? `?ou=${encodeURIComponent(ou)}` : ''}`),
  gpoBackups: (id) => request(`/api/gpos/${id}/backups`),
  backupGpo: (id) => request(`/api/gpos/${id}/backup`, { method: 'POST', body: {} }),
  restoreGpo: (id, backupId) => request(`/api/gpos/${id}/restore/${backupId}`, { method: 'POST', body: {} }),
  bitlocker: (q) => request(`/api/bitlocker${q || ''}`),
  bitlockerOne: (id) => request(`/api/bitlocker/${id}`),
  createBitlocker: (body) => request('/api/bitlocker', { method: 'POST', body }),
  stale: (days = 90) => request(`/api/stale?days=${days}`),
  staleCleanup: (body) => request('/api/stale/cleanup', { method: 'POST', body }),
  recycleBin: () => request('/api/recycle-bin'),
  restoreRecycle: (id) => request(`/api/recycle-bin/${id}/restore`, { method: 'POST', body: {} }),
  importUsers: (rows) => request('/api/import/users', { method: 'POST', body: { rows } }),
  exportPowershell: () => fetch('/api/export/powershell').then((r) => r.text()),
  exportCsharp: () => fetch('/api/export/csharp').then((r) => r.text()),
  securityHealth: () => request('/api/security/health'),
  saveSecurityHealth: (body) => request('/api/security/health', { method: 'PUT', body }),
  operators: () => request('/api/operators'),
  createOperator: (body) => request('/api/operators', { method: 'POST', body }),
  updateOperator: (id, body) => request(`/api/operators/${id}`, { method: 'PUT', body }),
  assumeOperator: (id) => request(`/api/operators/assume/${id}`, { method: 'POST', body: {} }),
  lapsGrants: () => request('/api/laps-grants'),
  createLapsGrant: (body) => request('/api/laps-grants', { method: 'POST', body }),
  logs: (q) => request(`/api/logs${q || ''}`),
  logsFile: () => fetch('/api/logs/file').then((r) => r.text())
}
